import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import "../styles/_index.scss";
import { ThemeProvider } from "@/context/ThemeContext";
import DashboardLayout from "@/layout/DashboardLayout";

const leagueSpartan = League_Spartan({
  variable: "--font-league-spartan",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${leagueSpartan.variable} antialiased`}>
        <ThemeProvider>
          <DashboardLayout> {children}</DashboardLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
